server:
  port: 9080

spring:
  schema:
    avro:
      schema-locations:
        - classpath:avro/user.avsc
        - classpath:avro/order.avsc
  cloud:
    schema-registry-client:
      endpoint: ${SCHEMA_REGISTRY:http://localhost:28081}
    stream:
      kafka:
        binder:
          brokers: ${BOOTSTRAP_SERVERS:localhost:29091,localhost:29092,localhost:29093}
          auto-add-partitions: true # (*) both user-service and event-service can create topic and add partitions
      source: users
      bindings:
        users-out-0:
          destination: com.spring.kafka.avro.newuser
          content-type: application/*+avro
          producer:
            partition-count: 3 # (*)
            #use-native-encoding: true
        orders-out-0:
          destination: com.spring.kafka.avro.neworder
          content-type: application/*+avro
          producer:
            partition-count: 3 # (*)
            #use-native-encoding: true

management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always
